### ISSUE TITLE
Adding a Pull Request Template 🚀 

### ISSUE THREAD

**Issue by aswinikalyan30** [SaiyamTuteja/Faculty_Evaluation_System#15]
### What's wrong with the existing documentation

Similar to the Issue template - Create one while someone raises a PR which describes 

- [ ] Is this a bug fix/enhancement/documentation change
- [ ] What are the changes made?
- [ ] Checklist for - part of gssoc, tested for any breaking changes and other relevant checks
- [ ] Issue for which you are raising a PR for

### Record

- [X] I agree to follow this project's Code of Conduct
- [ ] I'm a GSSOC'24 contributor
- [ ] I want to work on this issue

**Comment by aswinikalyan30** [comment]
@prajwaldp223 assigning this one to you, can you remove the code of conduct as it was taken up by another person
It is not right to just raise a PR without getting the issue assigned to you

**Comment by ritikaguptaa** [comment]
@aswinikalyan30  please assign this task to me.

**Comment by Kiran-pande-30** [comment]
Can you please assign the issue to me?

**Comment by aswinikalyan30** [comment]
Yes @prajwaldp223 , assigning to you

**Comment by prajwaldp223** [comment]
thank you!!
