### ISSUE TITLE
Feat: Give a unique name for the project and create a logo for the same

### ISSUE THREAD

**Issue by aswinikalyan30** [SaiyamTuteja/Faculty_Evaluation_System#16]
### Describe the feature

The current system is built for a specific college - make it as a generalised project with which any college can integrate

### Add ScreenShots

<img width="613" alt="image" src="https://github.com/SaiyamTuteja/Faculty_Evaluation_System/assets/76677408/bfef2988-bc46-4fc7-a54a-79cffc24d9e6">

### Record

- [X] I agree to follow this project's Code of Conduct
- [ ] I'm a GSSOC'24 contributor
- [ ] I want to work on this issue

**Comment by Arya-Hari** [comment]
Hi! Could you please provide a bit more info regarding the requirements of the project? As in, are we supposed to design a sign up page for a generic sign up or redesign the logo only? Thanks!

**Comment by aswinikalyan30** [comment]
It is only for the redesign of the logo. 
You can go through the Learn.md file to know more
Let me know if you're interested!

**Comment by aindree-2005** [comment]
@aswinikalyan30 I am experienced in Design and am in my uni's GDSC Design team. Can I work on this? I can send you ideas for the redesign over discord

**Comment by aswinikalyan30** [comment]
Hey @aindree-2005 , sure! assigning this to you

**Comment by aindree-2005** [comment]
![ProfPraisal](https://github.co@aswinikalyan30 aiyamTuteja/Faculty_Evaluation_System/assets/68018372/c5578359-a979-4450-a3cd-351ec841f37b)
@aswinikalyan30 does this look good? Then I'll make the pr

**Comment by aswinikalyan30** [comment]
This looks good, but the place this is going to go is right above the CUID that's mentioned in the issue description 
So can you make something with an icon and a text to the right?

**Comment by aindree-2005** [comment]
> This looks good, but the place this is going to go is right above the CUID that's mentioned in the issue description So can you make something with an icon and a text to the right?

As in something like the university logo? Got it

**Comment by aindree-2005** [comment]
![ProfPraisal (1)](https://github.com/SaiyamTuteja/Faculty_Evaluation_System/assets/68018372/9caaf7ba-b8ad-4e24-b7ac-9202d163357e)
How about this layout?

**Comment by aswinikalyan30** [comment]
Looks great! Go ahead and raise a PR - but can you also insert this in the code where the old logo was used? and add that screenshot in your PR
