### ISSUE TITLE
Feat: Adding regex for input fields

### ISSUE THREAD

**Issue by aswinikalyan30** [SaiyamTuteja/Faculty_Evaluation_System#17]
### Describe the feature

Add a regex for :

- CUID as an email (with a helper text telling it must contain an @ symbol
- Password (generic strong password rules)

### Add ScreenShots

<img width="328" alt="image" src="https://github.com/SaiyamTuteja/Faculty_Evaluation_System/assets/76677408/496128f0-cda6-4b96-9591-534bc74d5f23">

### Record

- [X] I agree to follow this project's Code of Conduct
- [ ] I'm a GSSOC'24 contributor
- [ ] I want to work on this issue

**Comment by Arya-Hari** [comment]
Hi! I would love to work on this issue. I have worked with HTML, CSS and JS for about a year now and I hope I can make a valid contribution to this issue! Thanks!

**Comment by aswinikalyan30** [comment]
Sure @Arya-Hari , it's yours! Happy contributing 🚀

**Comment by Pranav0606** [comment]
Willing to work on this issue!
Can you please reassign it to me?

**Comment by aswinikalyan30** [comment]
Sure @Pranav0606 , go ahead

**Comment by aswinikalyan30** [comment]
Hey @Pranav0606 , any updates on this?
