### ISSUE TITLE
Feat: Filter genuine email

### ISSUE THREAD

**Issue by pankaj-bind** [SaiyamTuteja/Faculty_Evaluation_System#21]
## Security Feature
In your application anyone can enter using **temporary or disposable email**.
I will add a feature so that no one could create an account using **temporary or disposable email**.
It will allow only genuine users in your database.
It will help to avoid any bot.
Assign me this work under GSSoC24, I will implement it.

### Add ScreenShots

.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by aswinikalyan30** [comment]
Hey Pankaj, thanks for opening this issue, can you describe the approach you are going to take to tackle this issue?

**Comment by aswinikalyan30** [comment]
Hey @pankaj-bind , if you can explain the approach I can go ahead and add the relevant labels

**Comment by pankaj-bind** [comment]
> Hey @pankaj-bind , if you can explain the approach I can go ahead and add the relevant labels

I will use an API which is free it will first checks is the email genuine or not, if yes then it proceeds otherwise, breaks operation and shows a popup "invalid email".
It is not like email verification using OTP.
e.g. [pankajbind30@gmail.com](mailto:pankajbind30@gmail.com) (this is a genuine email) and [mixat67435@losvtn.com](mailto:mixat67435@losvtn.com) (This is a temporary or disposable email). My solution identifies this.
I have tried this, and this feature is very unique.

**Comment by aswinikalyan30** [comment]
Great! Have assigned this to you already
You can start contributions!

**Comment by aswinikalyan30** [comment]
Hey, I don't see a PR , why have you closed it @pankaj-bind ?

**Comment by aswinikalyan30** [comment]
@sk-upadhyay Please see if you can take this up

**Comment by sk-upadhyay** [comment]
Okay, Thanks @aswinikalyan30

**Comment by sk-upadhyay** [comment]
@aswinikalyan30 Here i have been assigned for this

**Comment by sk-upadhyay** [comment]
@aswinikalyan30 what kind of changes do you see that I was not assigned I will undo it but please be specific.

**Comment by sk-upadhyay** [comment]
@aswinikalyan30 You can close this issue
