### ISSUE TITLE
To make the authentication system stronger, I make students and faculty to enter only the emails provided by the university. In addition to that I'll make this project available to many universities

### ISSUE THREAD

**Issue by Gayathri-Pavuluri** [SaiyamTuteja/Faculty_Evaluation_System#25]
To make the authentication system stronger, I make students and faculty to enter only the emails provided by the university. In addition to that I'll make this project available to many universities
@SaiyamTuteja    please assign this project for me.

_Originally posted by @Gayathri-Pavuluri in https://github.com/SaiyamTuteja/Faculty_Evaluation_System/issues/4#issuecomment-2110355015_

**Comment by aswinikalyan30** [comment]
Hey @Gayathri-Pavuluri , how are you tackling this? Because I see #21 similar to that, please setup the code in local and look at other issues you find too!

**Comment by aswinikalyan30** [comment]
Marking this as closed as there is no response
