### ISSUE TITLE
BUG: Absence of an SQL query for storing faculty sign-ups

### ISSUE THREAD

**Issue by RahulK4102** [SaiyamTuteja/Faculty_Evaluation_System#27]
Describe

here as you can see in the code there no logic written for storing the data if user type is set to faculty 
![Screenshot 2024-05-15 145815](https://github.com/SaiyamTuteja/Faculty_Evaluation_System/assets/119075798/1fc0c9f7-4673-4f88-9600-3d1213d1c4f1)
![Screenshot 2024-05-15 145900](https://github.com/SaiyamTuteja/Faculty_Evaluation_System/assets/119075798/14b41afa-f6b4-4c16-8a0a-430d7a369a15)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by RahulK4102** [comment]
@aswinikalyan30 Kindly assign me this issue under GSSOC'24

**Comment by aswinikalyan30** [comment]
Sure @RahulK4102 😀
