### ISSUE TITLE
Add Code of Conduct

### ISSUE THREAD

**Issue by sanjay-kv** [SaiyamTuteja/Faculty_Evaluation_System#3]
We recommend that every repo has a code of conduct. If you don’t feel comfortable creating your own Code of Conduct from scratch we highly recommend using one of the templates provided by GitHub. If you do use a template, please read through the template and ensure that you can and will abide by the Code of Conduct.

Please follow [these](https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/adding-a-code-of-conduct-to-your-project#adding-a-code-of-conduct-using-a-template) instructions on how to add a Code of Conduct.

Sample: https://github.com/Recode-Hive/Stackoverflow-Analysis/blob/main/CODE_OF_CONDUCT.md

**Comment by suhanipaliwal** [comment]
I would like to work on this issue. Please assign me this task.

**Comment by Passionatelytoooadorable** [comment]
Hi @sanjay-kv @SaiyamTuteja, I would like to add Code of Conduct. Please assign this to me.

**Comment by Passionatelytoooadorable** [comment]
> Hi @sanjay-kv @SaiyamTuteja, I would like to add Code of Conduct. Please assign this to me.

I request you to kindly please assign this issue to me. @sanjay-kv @SaiyamTuteja

**Comment by aswinikalyan30** [comment]
Hey @suhanipaliwal you can go ahead and work on this 
@Passionatelytoooadorable - you can see if you can contribute to #1

**Comment by prajwaldp223** [comment]
@aswinikalyan30  can i work on this ?
