### ISSUE TITLE
BUG: Not able to create student as class_id parameter of student_list is missing from the form

### ISSUE THREAD

**Issue by aswinikalyan30** [SaiyamTuteja/Faculty_Evaluation_System#31]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What went down?

<img width="1428" alt="image" src="https://github.com/SaiyamTuteja/Faculty_Evaluation_System/assets/76677408/3c4a165c-d09d-482b-95f4-5af38cd0271b">

The class_id is in the schema of the database in the student_list table (can find it in evaluation_db) but while inserting the record during signup it is not taken from the user
Hence, add it to the form and read the value from the form

### Record

- [X] I agree to follow this project's Code of Conduct
- [ ] I'm a GSSOC'24 contributor
- [ ] I want to work on this issue

**Comment by anushkasaxena07** [comment]
please assign this issue to me @aswinikalyan30

**Comment by aswinikalyan30** [comment]
Sure @anushkasaxena07

**Comment by aswinikalyan30** [comment]
This issue is open for contribution!

**Comment by aswinikalyan30** [comment]
@Pranav0606 here is the issue

**Comment by aswinikalyan30** [comment]
@Pranav0606 do you want to take it up?

**Comment by Pranav0606** [comment]
Yeah! 
I am interested @aswinikalyan30 !
