### ISSUE TITLE
BUG: Not able to run evaluation_db queries - value of Avatar cannot be set to null

### ISSUE THREAD

**Issue by aswinikalyan30** [SaiyamTuteja/Faculty_Evaluation_System#32]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What went down?

<img width="761" alt="image" src="https://github.com/SaiyamTuteja/Faculty_Evaluation_System/assets/76677408/6aaa713b-7a80-476d-9c9c-9800f85b9f70">

Modify the queries wherever "avatar" coloumn is present - change it to a **datatype** that can have the above default value

### Record

- [X] I agree to follow this project's Code of Conduct
- [ ] I'm a GSSOC'24 contributor
- [ ] I want to work on this issue

**Comment by Swapnilden** [comment]
i would love to work on this issue, could you please assign me this issue

**Comment by aswinikalyan30** [comment]
Sure @Swapnilden
