### ISSUE TITLE
Feat: Auto Commenting when an issue is closed by maintainer

### ISSUE THREAD

**Issue by Asymtode712** [SaiyamTuteja/Faculty_Evaluation_System#43]
### Describe the feature

This feature aims to solve the problem of poor communication and lack of acknowledgment when issues are closed. By automatically commenting on closed issues, it ensures that contributors are informed about the closure and are thanked for their efforts. This helps maintain a positive and engaging community atmosphere, encouraging continued contributions and fostering good relationships between maintainers and contributors.

### Add ScreenShots

![issue closed](https://github.com/SaiyamTuteja/Faculty_Evaluation_System/assets/115717746/c9522e99-5472-4b12-af9c-6de54a9894f3)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Asymtode712** [comment]
@aswinikalyan30 please assign me this issue under gssoc'24

**Comment by aswinikalyan30** [comment]
Sure.

**Comment by tanich04** [comment]
I want to work on this issue. please assign me this

**Comment by aswinikalyan30** [comment]
assigned it to you @Asymtode712
