### ISSUE TITLE
Feat: Workflow for closing old PRs

### ISSUE THREAD

**Issue by Asymtode712** [SaiyamTuteja/Faculty_Evaluation_System#44]
### Describe the feature

This feature aims to automate the management of open PRs in a repository, ensuring that outdated or abandoned PRs are closed in a timely manner. By doing so, it helps maintain repository hygiene, improves workflow efficiency, and provides a better experience for both maintainers and contributors.

**Comment by Asymtode712** [comment]
@aswinikalyan30 please assign me this issue under gssoc'24

**Comment by aswinikalyan30** [comment]
Sure
