### ISSUE TITLE
Change the UI Icons on signup page

### ISSUE THREAD

**Issue by Pranav0606** [SaiyamTuteja/Faculty_Evaluation_System#48]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What went down?

![image](https://github.com/SaiyamTuteja/Faculty_Evaluation_System/assets/97611449/a7418bc3-cb24-41cb-93fd-51cf9eccde10)

UI Elements plays an important role for user interaction. 
On signup page there are various input fields.
I have seen that most of them have the same icon which may be bit confusing for the user. 
I would like to change some icons on signup page to make it user friendly.
Assign this issue to me.

### Record

- [X] I'm a GSSOC'24 contributor
- [X] I agree to follow this project's Code of Conduct
- [X] I want to work on this issue

**Comment by aswinikalyan30** [comment]
Sure @Pranav0606 , assigning to you
