### ISSUE TITLE
Add Reset Password

### ISSUE THREAD

**Issue by mahek0620** [SaiyamTuteja/Faculty_Evaluation_System#52]
### Describe the feature

ADD FORGOT PASSWORD AND PROVIDE OPTION FOR LOGGING OR SIGNIN WITH GOOGLE

### Add ScreenShots

![Screenshot 2024-05-26 141408](https://github.com/SaiyamTuteja/Faculty_Evaluation_System/assets/136893675/f7494f1d-f25a-4e29-9f70-b35a3569398c)
![image](https://github.com/SaiyamTuteja/Faculty_Evaluation_System/assets/136893675/355fa92a-7860-4aa2-af7b-68169eaea2ad)
![image](https://github.com/SaiyamTuteja/Faculty_Evaluation_System/assets/136893675/e76af624-63fa-490a-b47e-4de442c84f44)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by mahek0620** [comment]
@aswinikalyan30 can you please assign this to me under gssoc'24

**Comment by aswinikalyan30** [comment]
Sure, go ahead @mahek0620

**Comment by deepanshi211** [comment]
@aswinikalyan30 can use please assign this issue to me .I am willing to work on this.

**Comment by Priyanshuomer** [comment]
@aswinikalyan30  Hi, can you please assign me this issue , I want to contribute on this .

**Comment by aswinikalyan30** [comment]
It's already worked upon, sorry!
