### ISSUE TITLE
Implementation of contact us page

### ISSUE THREAD

**Issue by mahek0620** [SaiyamTuteja/Faculty_Evaluation_System#54]
### Describe the feature

The website currently lacks a "Contact Us" page. This page is crucial for providing users with a direct means to reach out for support, feedback, or inquiries.

Solution: Implement a "Contact Us" Page

Create a New Page:
Develop a dedicated "Contact Us" page that can be easily accessed from the main navigation menu. This page should include:

A contact form for users to submit their inquiries directly through the website.
Relevant contact information such as email addresses, phone numbers, and physical addresses.
Links to social media profiles for additional means of contact.
Design the Contact Form:
Name
Email Address
Subject
Message
User Experience Enhancements:
Include a confirmation message to inform users that their message has been received.
Ensure that the "Contact Us" page is responsive and accessible on all devices.

### Add ScreenShots

![IMG_8504](https://github.com/SaiyamTuteja/Faculty_Evaluation_System/assets/136893675/aef84094-b31a-4bfc-9587-dc19db41f570)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by ParthNakum21** [comment]
Hello @SaiyamTuteja, I'm interested in contributing to the project by adding the Contact Us page. 
Could you please assign this task to me under GSSoC with appropriate level?

**Comment by aswinikalyan30** [comment]
This is a faculty evaluation system. Where do you intend to put this page? 
I don't feel this page is relevant to this project.

**Comment by ParthNakum21** [comment]
A contact form can be used for general inquiries. It provides users with a way to get in touch, ask questions, provide feedback, or request assistance.

**Comment by KASHISHROY** [comment]
Hello Sir,can you please assign this task to me?

**Comment by aswinikalyan30** [comment]
Ok. Assigned to you @ParthNakum21 
But really do feel this is not relevant to this project.

**Comment by aswinikalyan30** [comment]
The original person who raised this issue is @mahek0620 , so will be assigning to him. Others can raise a different issue
