### ISSUE TITLE
improving readme file 

### ISSUE THREAD

**Issue by meenakshiiyer2531** [SaiyamTuteja/Faculty_Evaluation_System#55]
### What's wrong with the existing documentation

In the readme file there is no way to understand how to run the project after forking. Kindly assign this issue to me for Gssoc '24 

### Add ScreenShots

![image](https://github.com/SaiyamTuteja/Faculty_Evaluation_System/assets/74537549/fc937d31-4fe4-4307-89b8-e939fd8f400c)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by aswinikalyan30** [comment]
@meenakshiiyer2531 , could you elaborate what all changes you would be making?

**Comment by meenakshiiyer2531** [comment]
I will be making the video visible so that everyone can refer to it for the database part. Then I would provide clear instructions on how they can implement the project. 
Even i have a small doubt @SaiyamTuteja.

**Comment by aswinikalyan30** [comment]
Instead of making video visible, you can capture screenshots from the already existing video and do a step-by-step approach
What is your doubt @meenakshiiyer2531 ?

**Comment by aswinikalyan30** [comment]
Hey @meenakshiiyer2531 any updates on this?

**Comment by meenakshiiyer2531** [comment]
Hello @aswinikalyan30 
I have raised PR refining the documentation part
Regards,
V Meenakshi Iyer
