### ISSUE TITLE
Feat: Auto comment when a pr is raised

### ISSUE THREAD

**Issue by aRUsh-codes** [SaiyamTuteja/Faculty_Evaluation_System#57]
### Describe the feature

This will add a feature to give instant comment to user after raising a PR

### Add ScreenShots

When we get comments on pull requests right after they're submitted, it shows us contributors that the admins are paying attention and appreciating our hard work. This helps create a friendly atmosphere where teamwork thrives, making everyone more likely to keep pitching in and staying involved.
This feature aims to address the problem of delayed and inconsistent communication following the raising of PRs
Could you please assign me this issue under GSSOC'24 and appropriate level too

Thank You

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by aswinikalyan30** [comment]
This is already implemented. Please check for other issues
