### ISSUE TITLE
Changing the name of the project

### ISSUE THREAD

**Issue by mahek0620** [SaiyamTuteja/Faculty_Evaluation_System#58]
### What's wrong with the existing documentation

 Update project title and headers in all documentation files.
 Modify project descriptions to reflect the new name.
 Perform a global search and replace for old project name (Faculty_Evaluation_System) to new project name.
 Update README.md and other Markdown files.
 Update configuration files with the new project name.
 Modify comments and code documentation.
 Review and test all changes.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by aswinikalyan30** [comment]
Sure go ahead

**Comment by mahek0620** [comment]
Here are the suggestions 
InstructIQ
TeachTrack
FacultySpectrum
FacultyFusion
TeachInsights
@aswinikalyan30 if you find any of the above good kindly tell else I will think something else

**Comment by aswinikalyan30** [comment]
There is ProfPraisal as per the logo already.

**Comment by aswinikalyan30** [comment]
Yes
