### ISSUE TITLE
"Username or password is incorrect" Error

### ISSUE THREAD

**Issue by Pranav0606** [SaiyamTuteja/Faculty_Evaluation_System#60]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What went down?

I have encountered an issue of "**Username or password is incorrect**" while user is entering correct credentials as well!
I am attaching some of the screen shots regarding the issues!

I have registered on the platform!
![image](https://github.com/SaiyamTuteja/Faculty_Evaluation_System/assets/97611449/622411f6-b0b0-457e-891e-d1fde75bfd52)

The database has been updated successfully!
![image](https://github.com/SaiyamTuteja/Faculty_Evaluation_System/assets/97611449/73150748-b349-4783-ba16-4ea03c0db976)

While I am trying to login!
![image](https://github.com/SaiyamTuteja/Faculty_Evaluation_System/assets/97611449/2cd5faeb-e944-48fa-860d-dda4bf06bd8e)

I would like to work on this issue!

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by aswinikalyan30** [comment]
There is an issue #31 for this.

**Comment by aswinikalyan30** [comment]
Will assign that to you
