### ISSUE TITLE
updating README file

### ISSUE THREAD

**Issue by mahek0620** [SaiyamTuteja/Faculty_Evaluation_System#64]
### What's wrong with the existing documentation

Adding contributors profile in readme file

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by aswinikalyan30** [comment]
Can't this be done with #59 ?

**Comment by mahek0620** [comment]
Sure, I will implement in #59 . Kindly change the labels accordingly
