### ISSUE TITLE
Adding a readme

### ISSUE THREAD

**Issue by khushi463-tyagi** [SaiyamTuteja/Faculty_Evaluation_System#8]
As a GSSOC'24 contributor, I want to contribute to the project by updating a proper readme file of the project as a readme file is your project's description and first look. So I hope you can assign me this task

**Comment by harikavaleti911** [comment]
I want to contribute myself to this project. So please assign this issue to me

**Comment by SaiyamTuteja** [comment]
@khushi463-tyagi okk you can do

**Comment by khushi463-tyagi** [comment]
thank you for assigning me i look forward to completing the task as soon as possible

**Comment by aswinikalyan30** [comment]
Hi @khushi463-tyagi 
It would be helpful if you also add a short video of the entire project, call out key functionalities of the project

**Comment by SuhainaFathimaM** [comment]
@khushi463-tyagi I want to contribute myself to this project. So please assign this issue to me.. because readme looks blank

**Comment by aswinikalyan30** [comment]
@SuhainaFathimaM , @khushi463-tyagi is already working on it, i suggest you to look at the repo and find more issues

**Comment by khushi463-tyagi** [comment]
@aswinikalyan30 okk i will look into it

**Comment by aswinikalyan30** [comment]
@harikavaleti911 you can check out other issues created!

**Comment by aswinikalyan30** [comment]
hey @SuhainaFathimaM , @harikavaleti911 - created a couple more issues do check them out!

**Comment by aswinikalyan30** [comment]
Hey @khushi463-tyagi - any updates on this?

**Comment by aasthakourav20** [comment]
Hey @SaiyamTuteja , this issue is still open . If not worked upon , kindly assign it to me under GSSoC'24 as Readme file plays an important role in any repo and create convenience to Users/Contributors .

**Comment by khushi463-tyagi** [comment]
@aswinikalyan30 Yha started a little work on this currently understanding project and downloaded requirements to run the project on my system and I am currently busy with my college exams too so my work is getting delayed but I will complete as soon as possible

**Comment by khushi463-tyagi** [comment]
@SaiyamTuteja @aswinikalyan30 
I don't know why I am facing this issue while opening the database in MYSQL
![WhatsApp Image 2024-05-19 at 00 59 43](https://github.com/SaiyamTuteja/Faculty_Evaluation_System/assets/66127538/6ce080ed-ee48-4e44-8720-3b77970e84b1)


Could you pls help me with this

**Comment by aswinikalyan30** [comment]
Hey @khushi463-tyagi - you can reach out to me on discord at ashgreninja#9907 if you are facing any issues

**Comment by khushi463-tyagi** [comment]
@aswinikalyan30 thanks!!

**Comment by khushi463-tyagi** [comment]
@Meetjain1 I have raised the pull request for readme already

**Comment by Meetjain1** [comment]
> @Meetjain1 I have raised the pull request for readme already

@khushi463-tyagi okk great.
