### ISSUE TITLE
[FEAT] : sign up

### ISSUE THREAD

**Issue by RahulK4102** [SaiyamTuteja/Faculty_Evaluation_System#9]
## Describe

Inside the Sign Up page the Form submission was not done 
![Screenshot 2024-05-11 174848](https://github.com/SaiyamTuteja/Faculty_Evaluation_System/assets/119075798/68a0e61d-9038-4750-8188-a22c60d1cf8a)

**Comment by RahulK4102** [comment]
@SaiyamTuteja Kindly assign me this issue under GSSOC'24

**Comment by aswinikalyan30** [comment]
Hi @RahulK4102 - can you explain a bit more on what you intend to do on the submit?

**Comment by Satwik-Kar** [comment]
This issue caught my eye, and I'm curious to dig in. Let's team up and crack this one together! Excited to work on it with you!
@RahulK4102 . Kindly assign me this issue under **GSSOC'24**

**Comment by aswinikalyan30** [comment]
@Satwik-Kar - I urge you to dig into the code and look at other enhancements/bugs 
If @RahulK4102 is interested to team up with you - I need you two to discuss and let me know which parts he is doing and which part you are doing 
Once that is discussed - I will go forward and assign the issues to you two

**Comment by RahulK4102** [comment]
@aswinikalyan30, the form data we were collecting from the user wasn't being stored in the database. I've already addressed this issue, so I'd like to request you to assign this issue to me as I already fixed the issue locally on my pc.

**Comment by aswinikalyan30** [comment]
Sure, go ahead @RahulK4102

**Comment by aswinikalyan30** [comment]
@Satwik-Kar : You can have a look at other issues!
